name: CI

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
      - uses: actions/checkout@v3.5.3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Install deps
        run: npm ci
      - name: Run lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Run tests
        run: npm run test
      - name: Publish
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          npx lerna init
          npx lerna version prerelease --no-private --no-git-tag-version --yes --exact --preid ${{ github.sha }}.${{ github.run_attempt }}
          npm publish --workspaces packages --access public --tag pr-${{ github.event.number }}
