name: CI

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - name: Install deps
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Run lint
        run: pnpm lint
      - name: Run tests
        run: pnpm test

  publish:
    if: ${{ github.event_name == 'pull_request' }}
    needs: build
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: pnpm
          registry-url: https://registry.npmjs.org
      - name: Install deps
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Publish
        run: |
          pnpm dlx lerna init
          pnpm dlx lerna version prerelease --no-git-tag-version --yes --exact --preid ${{ github.sha }}.${{ github.run_attempt }}
          pnpm --filter "./packages/*" publish --access public --no-git-checks --tag pr-${{ github.event.number }} --dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_CAPI_DEV }}
