name: CI

on:
  pull_request:
  merge_group:
  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: actions/cache@v3
        with:
          path: .turbo
          key: ${{ runner.os }}-${{ matrix.node-version }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-turbo-
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - name: Install deps
        run: pnpm install
      - name: Build
        run: pnpm turbo build --cache-dir=.turbo
      - name: Lint
        run: pnpm lint
      - name: Test
        run: pnpm test
      - name: Run Integration Tests
        run: pnpm test:ci

  pack:
    needs: build
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: actions/cache@v3
        with:
          path: .turbo
          key: ${{ runner.os }}-20.x-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-20.x-turbo-
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Setup Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: pnpm
          registry-url: https://registry.npmjs.org
      - name: Install deps
        run: pnpm install
      - name: Build
        run: pnpm turbo build --cache-dir=.turbo
      - name: Pack
        run: |
          pnpm dlx lerna init
          pnpm dlx lerna version prerelease --no-git-tag-version --yes --exact --preid ${{ github.sha }}.${{ github.run_attempt }}
          pnpm pack --dir packages/cli
          pnpm pack --dir packages/client
          pnpm pack --dir packages/codegen
          pnpm pack --dir packages/json-rpc/json-rpc-provider
          pnpm pack --dir packages/json-rpc/json-rpc-provider-proxy
          pnpm pack --dir packages/json-rpc/sc-provider
          pnpm pack --dir packages/json-rpc/logs-provider
          pnpm pack --dir packages/json-rpc/sm-provider
          pnpm pack --dir packages/json-rpc/ws-provider
          pnpm pack --dir packages/legacy-polkadot-provider
          pnpm pack --dir packages/node-polkadot-provider
          pnpm pack --dir packages/substrate-bindings
          pnpm pack --dir packages/substrate-client
          pnpm pack --dir packages/metadata-builders
          pnpm pack --dir packages/view-builder
          pnpm pack --dir packages/tx-helper
          pnpm pack --dir packages/utils
      - uses: actions/upload-artifact@v3
        with:
          name: package
          path: ./packages/cli/*.tgz
      - uses: actions/upload-artifact@v3
        with:
          name: package
          path: ./packages/client/*.tgz
      - uses: actions/upload-artifact@v3
        with:
          name: package
          path: ./packages/codegen/*.tgz
      - uses: actions/upload-artifact@v3
        with:
          name: package
          path: ./packages/json-rpc/json-rpc-provider/*.tgz
      - uses: actions/upload-artifact@v3
        with:
          name: package
          path: ./packages/json-rpc/json-rpc-provider-proxy/*.tgz
      - uses: actions/upload-artifact@v3
        with:
          name: package
          path: ./packages/json-rpc/sc-provider/*.tgz
      - uses: actions/upload-artifact@v3
        with:
          name: package
          path: ./packages/json-rpc/logs-provider/*.tgz
      - uses: actions/upload-artifact@v3
        with:
          name: package
          path: ./packages/json-rpc/sm-provider/*.tgz
      - uses: actions/upload-artifact@v3
        with:
          name: package
          path: ./packages/json-rpc/ws-provider/*.tgz
      - uses: actions/upload-artifact@v3
        with:
          name: package
          path: ./packages/legacy-polkadot-provider/*.tgz
      - uses: actions/upload-artifact@v3
        with:
          name: package
          path: ./packages/node-polkadot-provider/*.tgz
      - uses: actions/upload-artifact@v3
        with:
          name: package
          path: ./packages/substrate-bindings/*.tgz
      - uses: actions/upload-artifact@v3
        with:
          name: package
          path: ./packages/substrate-client/*.tgz
      - uses: actions/upload-artifact@v3
        with:
          name: package
          path: ./packages/metadata-builders/*.tgz
      - uses: actions/upload-artifact@v3
        with:
          name: package
          path: ./packages/view-builder/*.tgz
      - uses: actions/upload-artifact@v3
        with:
          name: package
          path: ./packages/tx-helper/*.tgz
      - uses: actions/upload-artifact@v3
        with:
          name: package
          path: ./packages/utils/*.tgz
