name: CI

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Install deps
        run: npm ci
      - name: Run lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Run tests
        run: npm run test

  publish:
    if: ${{ github.event_name == 'pull_request' }}
    needs: build
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: npm
          registry-url: https://registry.npmjs.org
      - name: Install deps
        run: npm ci
      - name: Build
        run: npm run build
      - name: Publish
        run: |
          npx lerna init
          npx lerna version prerelease --no-git-tag-version --yes --exact --preid ${{ github.sha }}.${{ github.run_attempt }}
          npm publish --workspace packages --access public --tag pr-${{ github.event.number }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_CAPI_DEV }}
