name: E2E Zombienet CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.5.3
      - uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - name: build
        run: |
          pnpm install
          pnpm turbo build --cache-dir=.turbo
      - name: Download Polkadot and parachain binaries
        run: |
          wget --no-verbose https://github.com/paritytech/polkadot-sdk/releases/download/polkadot-v1.9.0/polkadot
          wget --no-verbose https://github.com/paritytech/polkadot-sdk/releases/download/polkadot-v1.9.0/polkadot-parachain
          wget --no-verbose https://github.com/paritytech/polkadot-sdk/releases/download/polkadot-v1.9.0/polkadot-prepare-worker
          wget --no-verbose https://github.com/paritytech/polkadot-sdk/releases/download/polkadot-v1.9.0/polkadot-execute-worker
          chmod +x ./polkadot*
        working-directory: integration-tests/zombie-tests
      - name: Run a local relaychain using zombienet
        run: |
          export PATH=$(pwd):$PATH
          npx --yes @zombienet/cli@1.3.93 \
            --provider native \
            --dir zombienet_logs \
            spawn zombienet.native.toml \
            > polkadot.txt 2>&1 &
          source wait_until.sh 'curl -s "127.0.0.1:9933"'
          source wait_until.sh 'curl -s "127.0.0.1:9934"'
        working-directory: integration-tests/zombie-tests
      - name: Run test
        run: pnpm e2e
        working-directory: integration-tests/zombie-tests
      - name: Store logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: zombie-logs
          path: integration-tests/zombie-tests/zombienet_logs
