name: E2E Zombienet CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.5.3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: pnpm
      - name: build
        run: |
          pnpm install
          pnpm build
      - name: Get zombienet
        run: |
          curl -L -O https://github.com/paritytech/zombienet/releases/download/v1.3.68/zombienet-linux-x64
          chmod +x zombienet-linux-x64
      - name: Get polkadot
        run: |
          curl -L -O https://github.com/paritytech/polkadot-sdk/releases/download/polkadot-v1.1.0/polkadot
          chmod +x polkadot
      - name: Get polkadot execute worker
        run: |
          curl -L -O https://github.com/paritytech/polkadot-sdk/releases/download/polkadot-v1.1.0/polkadot-execute-worker
          chmod +x polkadot-execute-worker
      - name: Get polkadot prepare worker
        run: |
          curl -L -O https://github.com/paritytech/polkadot-sdk/releases/download/polkadot-v1.1.0/polkadot-prepare-worker
          chmod +x polkadot-prepare-worker
      - name: Get polkadot-parachain
        run: |
          curl -L -O https://github.com/paritytech/polkadot-sdk/releases/download/polkadot-v1.1.0/polkadot-parachain
          chmod +x polkadot-parachain
      - name: Run test
        run: |
          export PATH=$(pwd):$PATH
          ./zombienet-linux-x64 -p native test ./zombie-tests/src/0001-test.zndsl
